/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Car;
import Business.CarFleet;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riyamoitra
 */
public class AllCarsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CarFleet carFleet;
    /**
     * Creates new form AllCarsJPanel
     */
    public AllCarsJPanel(JPanel userProcessContainer, CarFleet carFleet) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carFleet = carFleet;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllCars = new javax.swing.JTable();
        btnViewCarDetails = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblAllCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand Name", "Model Number", "Serial Number", "No. of Seats", "Availibility", "year of manufacturing", "M.C Expiration date", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAllCars);
        if (tblAllCars.getColumnModel().getColumnCount() > 0) {
            tblAllCars.getColumnModel().getColumn(0).setResizable(false);
            tblAllCars.getColumnModel().getColumn(1).setResizable(false);
            tblAllCars.getColumnModel().getColumn(2).setResizable(false);
            tblAllCars.getColumnModel().getColumn(3).setResizable(false);
            tblAllCars.getColumnModel().getColumn(4).setResizable(false);
            tblAllCars.getColumnModel().getColumn(5).setResizable(false);
            tblAllCars.getColumnModel().getColumn(6).setResizable(false);
            tblAllCars.getColumnModel().getColumn(7).setResizable(false);
        }

        btnViewCarDetails.setText("View Car Details");
        btnViewCarDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCarDetailsActionPerformed(evt);
            }
        });

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewCarDetails)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCarDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewCarDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCarDetailsActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblAllCars.getSelectedRow();
        if(selectedRow < 0){
            
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view details", "Warning",JOptionPane.WARNING_MESSAGE);
            
        }
        else{
            Car car = (Car) tblAllCars.getValueAt(selectedRow, 0);
            
           
        
        ViewCarDetailsJPanel panel = new ViewCarDetailsJPanel(userProcessContainer , car);
        userProcessContainer.add("ViewCarDetailsJPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewCarDetailsActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewCarDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAllCars;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
    
        DefaultTableModel dtm = (DefaultTableModel) tblAllCars.getModel();
        dtm.setRowCount(0);
        
        for(Car car : carFleet.getCarFleet()){
            
            Object[] row = new Object[8];
            row[0]=car.getBrandName();
            row[1]=car.getModelNumber();
            row[2]=car.getSerialNumber();
            row[3]=car.getMax_seats();
            row[4]=car.isAvailable();
            row[5]=car.getYearOfManufacturing();
            row[6]=car.isMaintenenceCerticateExpiry();
            row[7]=car.getCity();
            
            dtm.addRow(row);
    
    }
    }
}

